shopkeeper/backend/shop/models.py
from django.db import models
from users.models import UserProfile
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.

class ShopCategory(models.Model):
	name = models.CharField(max_length = 255, null = True, blank = True)
	slug = models.SlugField(null = True, blank = True)
	image = models.ImageField(upload_to = 'images/shop_category/', null = True, blank = True)
	description = models.TextField(null = True, blank = True)
	added_on = models.DateTimeField(auto_now_add = True, null = True, blank = True)
	updated_on = models.DateTimeField(auto_now = True, null = True, blank = True)

	class Meta:
		ordering = ('-added_on',)
		verbose_name_plural = 'Shop Categories'

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.name)
		super(ShopCategory, self).save(*args, **kwargs)

	# def get_absolute_url(self):
	# 	return reverse('shop:shop_list_category', args = [str(self.slug)])


class Shop(models.Model):
	name = models.CharField(max_length = 255, null = True, blank = True)
	slug = models.SlugField(null = True, blank = True)
	owner = models.ForeignKey(UserProfile, on_delete = models.CASCADE)
	address = models.CharField(max_length = 255, null = True, blank = True)
	image = models.ImageField(upload_to = 'images/shop/', null = True, blank = True)
	description = models.TextField(null = True, blank = True)
	category = models.ManyToManyField(ShopCategory, blank = True)
	opening_date = models.DateTimeField(null = True, blank = True)
	added_on = models.DateTimeField(auto_now_add = True, null = True, blank = True)
	updated_on = models.DateTimeField(auto_now = True, null = True, blank = True)

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.name)
		super(Shop, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('shop:shop_detail', args = [str(self.slug)])











	

shopkeeper/backend/shop/forms.py
from django import forms
from .models import Shop


class ShopForm(forms.ModelForm):

	class Meta:
		model = Shop
		fields = ('name', 'address', 'image', 'description', 'category', 'opening_date')

shopkeeper/backend/shop/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from shop.models import Shop, ShopCategory
from shop.forms import ShopForm
from product.models import ProductCategory, Product

# Create your views here.

def shop_list(request, shop_category_slug = None):
	shop_categories = ShopCategory.objects.all()
	shops_dict = {}
	if shop_category_slug != None:
		shop_list = Shop.objects.filter(category__slug = shop_category_slug).order_by('-added_on')
		shops_dict['shop_list'] = shop_list
	else:
		shop_list = Shop.objects.all().order_by('-added_on')
		shops_dict['shop_list'] = shop_list

	context = {
		"shop_categories":shop_categories,
		"shops_dict":shops_dict,
	}
	
	return render(request, 'shop/shop_list.html', context)


def shop_detail(request, slug = None):
	shop_instance = Shop.objects.filter(slug = slug).last()
	shop_category = shop_instance.category.all().values_list('name', flat = True)
	shop_category = ", ".join(shop_category)
	products = Product.objects.all()
	# if product_category_slug is not None:
	# 	products = products.filter(slug = product_category_slug)

	shop_categories = ShopCategory.objects.all()

	context = {
		"shop_instance":shop_instance,
		"shop_category":shop_category,
		"products":products,
		"shop_categories":shop_categories
	}
	return render(request, 'shop/shop_detail.html', context)


@login_required(login_url = 'users:login_user')
def shop_create(request):
	if request.method == "POST":
		form = ShopForm(request.POST, request.FILES)
		print('before form valid')
		print(request.POST['category'])
		if form.is_valid():
			shop = form.save(commit = False)
			shop.owner = request.user
			shop.save()
			form.save_m2m()
			return redirect('/')
		return HttpResponse('form is not valid')
	else:
		form = ShopForm()

	shop_categories = ShopCategory.objects.all().order_by('-added_on')

	context = {
		"form":form,
		"shop_categories":shop_categories
	}
	return render(request, 'shop/shop_create.html', context)


def shop_edit(request, slug = None):
	shop_instance = Shop.objects.filter(slug = slug).last()
	if request.method == "POST":
		form = ShopForm(request.POST, request.FILES, instance = shop_instance)
		if form.is_valid():
			shop = form.save(commit = False)
			shop.owner = request.user
			shop.save()
			return 
	else:
		form = ShopForm(instance = shop_instance)
	context = {
		"form":form,
		"shop_instance":shop_instance,
	}
	return render(request, 'shop/shop_edit.html', context)

shopkeeper/frontend/templates/shop/shop_create.html
{% extends 'landing/main/base.html' %}
{% block content %}
	<form method = "POST" enctype="multipart/form-data">
		{% csrf_token %}
		<label>Name:</label>
		<input class="form-group" type="text" name="name"><br>
		<label>address:</label>
		<input type="text" name="address"><br>
		<label>Image:</label>
		<input type="file" name="image" accept="image/*" id="id_image"><br>
		<label for="id_description">Description:</label><br>
		<textarea name="description" cols="40" rows="10" id="id_description"></textarea><br>
		<label for="id_category">Category:</label><br>
		<select name="category" id="id_category" multiple>
		{% for category in shop_categories %}
		  <option value="{{ category.id }}">{{ category.name }}</option>
		{% endfor %}
		</select><br>
		<label for="id_opening_date">Opening date:</label><br>
		<!-- <input type="text" name="opening_date" id="id_opening_date"><br><br> -->
		<input type="submit" name="submit" value="Submit">
	</form>
{% endblock %}

shopkeeper/frontend/templates/shop/shop_detail.html
{% extends 'landing/main/base.html' %}

{% block content %}
<style type="text/css">
	h1, p {
		color: #eee;
	}
</style>

<div class="row" style="background-color: #282c3f">
	<div class="col-sm-3">
		<img src="{{ shop_instance.image.url }}" alt="{{ shop_instance.name }}" width="300" height="300">
	</div>
	<div class="col-sm-6">
		<h1>{{ shop_instance.name }}</h1>
		<p>Description: {{ shop_instance.description }}</p>
		<p>Address: {{ shop_instance.address }}</p>
		<p>Category: {{ shop_category }}</p>
	</div>
	<div class="col-sm-3">
		<h1><a href="{% url 'product_list' %}">All Product</a></h1>
	</div>
</div>
<div style="margin-top: 10px">
	{% for product in products %}
		{{ product.name }}<br>
	{% endfor %}
</div>

{% endblock %}

shopkeeper/frontend/templates/shop/shop_edit.html
{% extends 'landing/main/base.html' %}
<head>
	<title></title>
</head>
{% block content %}
	<form method = "POST">
		{% csrf_token %}
		<label for="id_name">Name:</label><br>
		<input type="text" name="name" value="{{ shop_instance.name }}" maxlength="255" id="id_name"><br>
		<label for="id_address">Address:</label><br>
		<input type="text" name="address" value="{{ shop_instance.address }}" maxlength="255" id="id_address"><br>
		<label for="id_image">Image:</label><br>
			Currently: <a href="{{ shop_instance.image.url }}">{{ shop_instance.image.url }}</a><br>
		<input type="file" name="image" accept="image/*" id="id_image"><br><br>
		<input type="submit" name="submit" value="update">
	</form>
{% endblock %}
</html>

shopkeeper/frontend/templates/shop/shop_list.html
{% extends 'landing/main/base.html' %}
<head>
	<title></title>
	
</head>
<body>
	<div>
		{% block content %}
		<div class="container">
			<div class="row">
				{% for shop in shops_dict.shop_list %}
					<div class="col-sm-3">
						<div>
							<a href="{% url 'shop_detail' shop.slug %}">
								{% if shop.image %}
									<img src="{{ shop.image.url }}" alt="{{ shop.name }}" style="width: 100%; height: 100%;">
								{% endif %}
								<h4>{{ shop.name }}</h4>
							</a>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
		{% endblock %}

	</div>

</body>
</html>