shopkeeper/backend/users/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin

class UserProfileManager(BaseUserManager):

	def create_user(self, email, name, username, password = None):
		if not email:
			raise ValueError("User must have email address")

		user = self.model(
				name = name,
				username = username,
				email = self.normalize_email(email),
			)
		user.set_password(password)
		user.save(using = self._db)

		return user

	def create_superuser(self, email, name, username, password):
		if not email:
			raise ValueError("User must have email address")

		user = self.create_user(
				name = name,
				username = username,
				email = email,
				password = password
			)

		user.is_superuser = True
		user.is_admin = True
		user.is_staff = True
		user.save(using = self._db)

		return user


class UserProfile(AbstractBaseUser, PermissionsMixin):
	email = models.EmailField(max_length = 255, null = True, blank = True, unique = True)
	name = models.CharField(max_length = 255, null = True, blank = True)
	username = models.CharField(max_length = 255, null = True, blank = True)
	is_staff = models.BooleanField(default = False)
	is_admin = models.BooleanField(default = False)

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username', 'name']

	objects = UserProfileManager()

	def __str__(self):
		return self.email

	def get_full_name(self):
		# user is identified by email
		return self.email

	def get_short_name(self):
		# user is identified by email
		return self.email

shopkeeper/backend/users/forms.py
from django import forms
from users.models import UserProfile

class RegistrationForm(forms.ModelForm):
	email = forms.EmailField(widget = forms.TextInput, label = 'email')
	password1 = forms.CharField(widget = forms.PasswordInput, label = 'password1')
	password2 = forms.CharField(widget = forms.PasswordInput, label = 'password2')

	class Meta:
		model = UserProfile
		fields = ('email',)

	def clean_email(self):
		email = self.cleaned_data.get('email')
		qs = UserProfile.objects.filter(email = email)
		if qs.exists():
			raise forms.ValidationError('Email already exists')
		return email

	def clean_password(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')
		if password1 and password2 and password1 != password2:
			raise forms.ValidationsError('Password doesnot match')
		return password2

	def save(self, commit = True):
		user = super(RegistrationForm, self).save(commit = False)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()
		return user


class AuthenticationForm(forms.Form):
	email = forms.EmailField(widget = forms.TextInput, label = 'email')
	password = forms.CharField(widget = forms.PasswordInput, label = 'password')

	class Meta:
		fields = ('email', 'password1')

	def clean_email(self):
		email = self.cleaned_data.get('email')
		if email and not UserProfile.objects.filter(email = email).exists():
			raise ValidationError('Email Id doesnot exist')
		return self.cleaned_data

shopkeeper/backend/users/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import authenticate, login, logout
from users.models import UserProfile
from users.forms import RegistrationForm, AuthenticationForm

# Create your views here.

def register(request):
	if request.method == "POST":
		form = RegistrationForm(request.POST)
		print('before form')
		if form.is_valid():
			print('after form')
			email = request.POST['email']
			password1 = request.POST['password1']
			print(email)
			if UserProfile.objects.filter(email = email).exists():
				print('email already exist')
				return HttpResponse('email already exist')
			else:
				user = form.save()
				login(request, user)
				return redirect('/')
	else:
		form = RegistrationForm()
	context = {
		'form':form
	}
	# return render(request, 'users/base.html', context)
	return HttpResponse('success')


def login_user(request):
	if request.method == "POST":
		form = AuthenticationForm(request.POST)
		if form.is_valid():
			email = request.POST['email']
			password = request.POST['password']
			user = authenticate(request, email = email, password = password)
			if user is not None:
				login(request, user)
				return redirect('/')
			return HttpResponse('You are not registered or check your email and password again')
	else:
		form = AuthenticationForm()
	context = {
		'form':form
	}
	return render(request, 'users/login.html', context)


def logout_user(request):
	logout(request)
	return redirect('/')

shopkeeper/frontend/templates/users/login.html
<!-- The Modal -->
<div class="modal fade" id="myModal_login">
<div class="modal-dialog">
  <div class="modal-content">
  
    <!-- Modal Header -->
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">×</button>
      <h4 class="modal-title">Login Form</h4>
    </div>
    
    <!-- Modal body -->
    <div class="modal-body">
    	<form action="{% url 'login_user' %}" method="POST">
    		{% csrf_token %}
          <label for="id_email">Email</label><br>
          <input type="text" name="email" id="id_email"><br>

          <label for="id_password">Password</label><br>
          <input type="password" name="password" id="id_email"><br>
          <br>
          <input type="submit" name="submit" value="login">
    	</form>
    </div>
    
    <!-- Modal footer -->
    <div class="modal-footer">
      <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
    </div>
    
  </div>
</div>
</div>

shopkeeper/frontend/templates/users/signup.html
<div class="modal fade" id="myModal_signup">
    <div class="modal-dialog">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">×</button>
          <h4 class="modal-title">Sign Up Form</h4>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
        	<form action="{% url 'register' %}" method="POST">
        		{% csrf_token %}
	          <label for="id_email">Email</label><br>
	          <input type="text" name="email" id="id_email"><br>

	          <label for="id_password1">Password1</label><br>
	          <input type="password" name="password1" id="id_password1"><br>

	          <label for="id_password2">Password2</label><br>
	          <input type="password" name="password2" id="id_password2"><br>
            <br>
	          <input type="submit" name="submit" value="Sign Up">  
        	</form>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
        
      </div>
    </div>
</div>

shopkeeper/frontend/templates/users/username.html
<!DOCTYPE html>
<html>
<head>
	<title>Username</title>
</head>
<body>
	<h1>Registeration form</h1>
	<form action="{% url 'register' %}" method = "POST">
		{% csrf_token %}
		<tr>
			<th>
				<label for="id_email">email:</label>
			</th>
			<td>
				<input type="text" name="email" required id="id_email">
			</td>
			<br>
		</tr>
		<tr>
			<th>
				<label for="id_password1">password1:</label>
			</th>
			<td>
				<input type="password" name="password1" required id="id_password1">
			</td><br>
		</tr>
		<tr>
			<th>
				<label for="id_password2">password2:</label>
			</th>
			<td>
				<input type="password" name="password2" required id="id_password2">
			</td><br>
		</tr>
		<input type="submit" name="submit" value = "submit">
	</form>
</body>
</html>